sonar.projectKey=Corei913th_formatrack_project
sonar.organization=corei913th

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=formatrack_project
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=formatrack_api,formatrack_frontend
sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/storage/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# PHP Coverage (optional but recommended)
sonar.php.coverage.reportPaths=formatrack_api/coverage.xml
