name: Frontend CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  validate:
    name: 🧹 Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Installation de pnpm
        run: npm install -g pnpm

      - name: 📥 Installation des dépendances
        working-directory: ./formatrack_frontend
        run: pnpm install

      - name: 🔍 Analyse statique (Lint)
        working-directory: ./formatrack_frontend
        run: pnpm run lint

      - name: ⌨️ Vérification des types (TypeScript)
        working-directory: ./formatrack_frontend
        run: pnpm exec tsc -b

  build:
    name: 📦 Vérification du Build
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Installation de pnpm
        run: npm install -g pnpm

      - name: 📥 Installation des dépendances
        working-directory: ./formatrack_frontend
        run: pnpm install

      - name: 🏗️ Compilation de production (Build)
        working-directory: ./formatrack_frontend
        run: pnpm run build
